import { Router } from 'express';
import { validateHandler } from '../../libs/routes';
import { authMiddleWare } from '../../libs/routes';
import Controller from './Controller';
import validateConfig from './validate';
export const traineeRouter: Router = Router();
traineeRouter.get('/', authMiddleWare('trainee1', 'read'), Controller.get);
traineeRouter.post('/', validateHandler(validateConfig.create), Controller.create);
traineeRouter.put('/', validateHandler(validateConfig.update), Controller.update);
traineeRouter.delete('/:id', validateHandler(validateConfig.delete), Controller.delete);
